services:
  database:
    image: 'mysql:latest'
    ports:
      - 3310:3306  # Map host port 3309 to container port 3306
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'  # Root password
      - 'MYSQL_DATABASE=ecom'  # Database name
      - 'MYSQL_USER=root'  # Database user
      - 'MYSQL_PASSWORD=root'  # Database user password
    volumes:
      - '~/volumes/ecom/mysql:/var/lib/mysql'  # Persist MySQL data

    